---
fail_fast: false

repos:
  - repo: meta
    hooks:
      - id: identity
      - id: check-hooks-apply
  # Protect secrets using Gitleaks
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.3
    hooks:
      - id: gitleaks
  # Spell check
  - repo: https://github.com/crate-ci/typos
    rev: typos-dict-v0.11.20
    hooks:
      - id: typos
  # Supported base hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  # Markdown lint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
        args: [-c, .markdownlint.yml]
        types: [file]
        files: .(md|qmd)$
